# Generated by Django 6.0.5 on 2026-05-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="max_threshold",
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name="sensor",
            name="min_threshold",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="sensor_type",
            field=models.CharField(
                choices=[
                    ("temperature", "Температура"),
                    ("humidity", "Влажность"),
                    ("pressure", "Давление"),
                    ("dustiness", "Запыленность"),
                    ("ph", "Кислотность pH"),
                    ("servo_angle", "Угол поворота сервопривода"),
                    ("motor_speed", "Скорость моторчика"),
                ],
                max_length=50,
            ),
        ),
    ]
